import pandas as pd
import matplotlib.pyplot as plt
import data



# Load the data into a Pandas DataFrame
data = pd.read_csv('waste_data.csv')

# Calculate the total waste generated by type
waste_by_type = data.groupby('Type of Waste')['Quantity (kg)'].sum()

# Create a bar chart of the total waste generated by type
plt.bar(waste_by_type.index, waste_by_type.values)
plt.xlabel('Type of waste')
plt.ylabel('Total quantity generated (kg)')
plt.title('Total amount of waste generated by type')
plt.show()

# Calculate the percentage of waste generated by type
waste_by_type_pct = waste_by_type / waste_by_type.sum() * 100

# Create a pie chart of the percentage of waste generated by type
plt.pie(waste_by_type_pct.values, labels=waste_by_type_pct.index, autopct='%1.1f%%')
plt.title('Percentage of waste generated by type')
plt.show()

# Calculate the percentage of waste generated by source
waste_by_source = data.groupby('Source')['Quantity (kg)'].sum()
waste_by_source_pct = waste_by_source / waste_by_source.sum() * 100

# Create a pie chart of the percentage of waste generated by source
plt.pie(waste_by_source_pct.values, labels=waste_by_source_pct.index, autopct='%1.1f%%')
plt.title('Percentage of waste generated by source')
plt.show()